# Overview {.unnumbered}

This chapter is a collection of sequencing examples that are as close as possible to the CDT, without all the details. The objecive is to prepare a library on which more realistic, and eventually forward-looking examples can be based. Our intention is not only to address today's scheduling problems, but also to prepare the ground for scheduling challenges of the next 5 to 10 years, where data and compute volumes will increase by several orders of magnitude---outstanding examples are [SKA](https://www.skao.int/en) and CERN's [FCC](https://home.cern/science/accelerators/future-circular-collider).

The chapter is divied into deterministic (D1 to D4) and stochastic (S1 to S3) scenarios.  Realistic cases are presented in the Use-Cases chapter.



## D1. Simplified Supply Chain Examples

Putting together:

- primal problem,
- dual problem,
- sensitivity analysis.

See [Example D1](examples/D1a_SC_simple.ipynb) and  [Example D1a](examples/D1b_SC_4_stage.ipynb)

These supply chain examples have the following structure.

```{mermaid}
graph LR
    A["Suppliers"] -->  B["Factories"] 
    B --> C["Warehouses"] 
    C --> D["Retailers"] 
```


```{mermaid}
%%{init: {'flowchart': {'curve': 'linear'}}}%%
flowchart LR
  subgraph SUP["Suppliers"]
    S1["$$S_1$$"]
    S2["$$S_2$$"]
    S3["$$S_3$$"]
  end
  subgraph FAC["Factories"]
    F1["$$F_1$$"]
    F2["$$F_2$$"]
    F3["$$F_3$$"]
  end
  subgraph WAR["Warehouses"]
    W1["$$W_1$$"]
    W2["$$W_2$$"]
    W3["$$W_3$$"]
  end
  subgraph RET["Retailers"]
    R1["$$R_1$$"]
    R2["$$R_2$$"]
    R3["$$R_3$$"]
  end

  S1 --> F1
  S1 --> F2
  S1 --> F3

  F1 --> W1
  F1 --> W2
  F1 --> W3

  W1 --> R1
  W1 --> R2 
  W1 --> R3

  style SUP fill:#EEEDFE,stroke:#AFA9EC,color:#3C3489
  style FAC fill:#E1F5EE,stroke:#5DCAA5,color:#085041
  style WAR fill:#FAEEDA,stroke:#EF9F27,color:#633806
  style RET fill:#FAECE7,stroke:#F0997B,color:#993C1D

  classDef purple fill:#EEEDFE,stroke:#AFA9EC,color:#3C3489
  classDef teal   fill:#E1F5EE,stroke:#5DCAA5,color:#085041
  classDef amber  fill:#FAEEDA,stroke:#EF9F27,color:#633806
  classDef coral  fill:#FAECE7,stroke:#F0997B,color:#993C1D

  class S1,S2,S3 purple
  class F1,F2,F3 teal
  class W1,W2,W3 amber
  class R1,R2,R3 coral
```

```{mermaid}
graph LR
    A["Instruments"] -->  B["HPC centres"] 
    B --> C["Data centres"] 
    C --> D["End-users"] 
```

## D2. Simplified Scheduling Examples

The scheduling [Example D2](examples/D2_sched-intro.ipynb) covers a lot of ground. We study a classical scheduling problem, where we are given a set of jobs, their release times, their durations and their due times. The objective is to optimize the makespan, or total duration of all the jobs.

We study:

- empirical scheduling (LIFO, EDD, SPT);
- key performance indicators (KPI);
- single-machine and multiple-machine scheduling;
- disjunctive scheduling using Big-M and convex hull approaches.


## D3. Simplified RCPSP Example

We are now in a position to add resource constraints to the scheduling problems above. The optimization is now more complex, since the resource constraints have to be simultaneously satisfied while minimizing the makespan, or any function of the makespan.

In  [Example D3]() we put together:

- resource constraints,
- precedence relations,
- time-indexed formulation,
- disjunctive approach.


Coming soon...

## D4. Simplified MRCPSP Example

In this example we have 4 jobs, 2 possible modes, 1 renewable resource and no non-renewable resources. Jobs 2 and 3 can be executed in mode 1 or in mode 2.

::: {#fig-mrcp}
```{mermaid}
graph LR
    A["$$J_0$$"] --> B("$$J_1$$")
    A --> C("$$J_2$$")
    B --> D("$$J_3$$")
    C --> E("$$J_4$$")
    D --> F["$$J_5$$"]
    E --> F

```
A project network represented as a directed acyclic graph (DAG) for a workflow with 4 processing jobs $J_1,\cdots, J_4.$ The tasks 0 and 5 are dummy tasks, representing the start and the end of the workflow.
:::

The project instance, shown above, is detailed in Table 1, where $S_j$ is the successor list of job $j,$ $m$ is the mode, $d_{jm}$ is the duration of job $j$ in mode $m,$ $k^{\rho}_{jm1}$ is the renewable resource requirement, $R^{\rho}$ is the renewable resource list, $K^{\rho}$ is the renewable resource limit, and $R^{\nu}$ is the non-renewable resource list, taken as empty. In other words we have 4 jobs, 2 possible modes, 1 renewable resource and no non-renewable resources. Jobs 2 and 3 can be executed in mode 1 or in mode 2. Jobs 0 and 5 are the source and sink respectively, with zero duration and zero resources.

$$\begin{aligned}
& \text {Table 1. Multi-mode RCPSP for a 4-job, 2-mode workflow. }\\
&\begin{array}{cccccccc}
%\begin{tabular}{|c|c|c|c|c|c|c|c|}
\hline 
j & S_{j}& m & d_{jm} & k^{\rho}_{jm1} & R^{\rho} & K^{\rho}_{1} & R^{\nu}\\
\hline 
0 & \left\{ 1,2\right\}  & 1 & 0 & 0 & \left\{ 1\right\}  & 3 & \emptyset \\
1 & \left\{ 3\right\}  & 1 & 2 & 2  &  &  & \\
2 & \left\{ 4\right\}  & 1 & 2 & 2 &  &  & \\
 &  & 2 & 3 & 1 &  &  & \\
3 & \left\{ 5\right\}  & 1 & 1 & 3 &  &  & \\
 &  & 2 & 2 & 1 &  &  & \\
4 & \left\{ 5\right\}  & 1 & 2 & 3 &  &  & \\
5 & \emptyset & 1 & 0 & 0 &  &  & \\
\hline 
%\end{tabular}
\end{array}
\end{aligned}$$

**Input File**

The simplest input file is a direct transcription of the table of variables.

```{json}
{
  "0":{"suc":("1","2"),"mod":"A","drt":0,    "rsc":0},
  "1":{"suc":"3","mod":"A",      "drt":2,    "rsc":2},
  "2":{"suc":"4","mod":("A","B"),"drt":[2,3],"rsc":[2, 1]},
  "3":{"suc":"5","mod":("A","B"),"drt":[1,2],"rsc":[3, 1]},
  "4":{"suc":"5","mod":"A",      "drt":2,    "rsc":3},
  "5": {"suc":"","mod":"A",      "drt":0,    "rsc":0 }
}
```

```{.python}
import json

with open("input.json", "r") as jsonfile: 
    TASKS = json.load(jsonfile)
```

Though, for interoperability, we should privilege the data model format, described above in **CDT-Implementation**. 


---

---


## S1. Two-Stage Stochastic

TBC

## S2. Multi-Stage Stochastic

TBC

## S3. Risk Measures

As presented in the [Risk Measures](./th-stochastic.qmd#risk-measures) section, there are various ways to include risk in the cost function. In this [example](./examples/03-OPF_risk.ipnb), we analyze a stochastic  energy dispatch problem, and compare the following risk measures:

- mean,
- CVaR,
- mean-variance,
- exponential.


